### ISSUE TITLE
where is the  LTSpice model of  diode of BAS16?

### ISSUE THREAD

**Issue by zzsczz** [CosmicPi/psutest#1]
bas16gw.lib is missing

**Comment by pingud98** [comment]
Thanks for the feedback, I'm afraid we stopped looking at a CW based converter as it was hard to get the ripple out, and the SiPM we were targetting has been discontinued. We are building a new small run of boards for testing using the MAX5026 IC. You can find details of the new power supply circuit we are using here: https://pdfserv.maximintegrated.com/en/an/AN895.pdf

As for the missing file, you can find it here: https://assets.nexperia.com/documents/spice-model/BAS16GW.txt but it will need to be re-imported into your spice environment, with the method depending upon your OS platform.
